### ISSUE TITLE
import example in README is broken

### ISSUE THREAD

**Issue by reece** [flupke/cython-setuptools#2]
I think there are two issues.

First, the example in `README.`md says `from cysetuptools import setup`. This package doesn't exist. Instead, I think you meant `from cython_setuptools ...`. This probably reflects a package renaming.

Second, there's no `setup` in `cython_setuptools.__init__.py`, so you can't import even after renaming. I suspect you want to add `from .vendor import setup` in `__init__.py`.

When I use `from cython_setuptools.vendor import setup` in `setup.py`, things seem to work.

**Comment by lrouch-gpsw** [comment]
cython-setuptools is meant to be vendored in your project, which is explained at the beginning fo the readme:

First install the cython-setuptools vendor module in the package, next to setup.py.

```
$ cd your-python-project/
$ cython-setuptools install
```

**Comment by reece** [comment]
Indeed, I missed that. Thanks for the quick reply!
